AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Resources:
  PutOrderFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: handler.put_order
      Runtime: python3.9
      CodeUri: .
      Policies:
        - Statement:
            - Sid: EventBridgePutEvents
              Effect: Allow
              Action:
                - events:PutEvents
              Resource: '*'
      Events:
        PutOrderAPI:
          Type: Api
          Properties:
            Path: /order
            Method: POST
      MemorySize: 3008
      Timeout: 30
Outputs:
  TestingAPI:
    Description: API Gateway endpoint URL for Prod stage for Order function
    Value: !Sub https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/order